import { gptUrl } from './gpt-content.js';

export const deckbuilderBalanceChecklist = {
  hero: {
    eyebrow: 'Ragtag Throne · Playbook',
    headline: 'Card System Design Checklist for Roguelike Deckbuilders',
    subhead:
      'A practical checklist for designing cards that create meaningful decisions, support combos, avoid dead hands, and stay manageable enough to build into a playable MVP.',
    primaryCta: {
      label: 'Open Roguelike Deckbuilder Designer GPT',
      href: gptUrl,
    },
    secondaryCta: {
      label: 'Read the MVP Playbook',
      href: '/playbooks/roguelike-deckbuilder-mvp/',
    },
  },

  promise:
    'A practical checklist for designing cards that create meaningful decisions, support combos, avoid dead hands, and stay manageable enough to build into a playable MVP.',

  sections: [
    {
      number: 1,
      title: 'Every card needs a job',
      paragraphs: [
        'Before writing flavor or naming the card, define its design role.',
        'A card should usually be one of these:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Core action',
            'Combo starter',
            'Combo payoff',
            'Resource generator',
            'Card draw',
            'Defense',
            'Scaling engine',
            'Risk/reward card',
            'Status applicator',
            'Status payoff',
            'Deck manipulation',
            'Enemy disruption',
            'Curse',
            'Rare build-around',
          ],
        },
        {
          type: 'labeled',
          label: 'Weak card',
          lines: ['Deal 7 damage.'],
        },
        {
          type: 'labeled',
          label: 'Better card',
          lines: [
            'Deal 7 damage. If this is your first Attack this turn, draw 1 card.',
            'Role: Tempo starter.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Can I explain why this card exists?',
            'Does it support an archetype?',
            'Does it create a decision?',
            'Does it interact with at least one broad tag or system?',
            'Would the deck lose anything interesting if this card was removed?',
          ],
        },
      ],
      rule: null,
      closingParagraphs: ['If the answer is no, cut it or merge it with another card.'],
    },
    {
      number: 2,
      title: 'Avoid dead-card design',
      paragraphs: [
        'A dead card is a card the player draws but cannot reasonably use.',
        'Some dead cards are fine. Too many dead cards make the game feel broken.',
        'High-risk dead-card patterns:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Only works against one enemy.',
            'Only works on one exact turn.',
            'Only works after one exact card.',
            'Only works in one exact biome.',
            'Only works if the player already has a rare combo piece.',
            'Only works when the player is already winning.',
            'Only works when the player is already losing badly.',
          ],
        },
        {
          type: 'labeled',
          label: 'Better patterns',
          lines: [
            'Works with a broad tag.',
            'Works with a common resource.',
            'Works with several card types.',
            'Works as a weak baseline but has a stronger conditional upside.',
            'Works defensively even when the combo is missing.',
          ],
        },
        {
          type: 'labeled',
          label: 'Bad',
          lines: ['Gain +5 power against Goblin Tax Collector.'],
        },
        {
          type: 'labeled',
          label: 'Better',
          lines: ['Gain +3 power against enemies with Shield or Pressure.'],
        },
        {
          type: 'labeled',
          label: 'Best',
          lines: [
            'Gain +2 power. Gain +2 more if the enemy has Shield or Pressure.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Can this card be played in most normal fights?',
            'Does it still do something if its combo condition is missing?',
            'Is the condition broad enough to appear often?',
            'Is this card allowed to be narrow because it is rare, cursed, or sideboard-style tech?',
          ],
        },
      ],
      rule: 'Most cards should be useful in 60 to 70 percent of normal turns.',
    },
    {
      number: 3,
      title: 'Use tags to create depth',
      paragraphs: [
        'Tags are how a small card pool creates big combinations.',
        'Good tags are broad and reusable.',
        'Examples:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Attack',
            'Skill',
            'Power',
            'Quick',
            'Heavy',
            'Combo',
            'Draw',
            'Discard',
            'Block',
            'Pressure',
            'Burn',
            'Poison',
            'Shield',
            'Tempo',
            'Clutch',
            'Risk',
            'Setup',
            'Payoff',
          ],
        },
        {
          type: 'labeled',
          label: 'For a football deckbuilder',
          lines: [
            'Pass',
            'Run',
            'Quick',
            'Deep',
            'Middle',
            'Outside',
            'Blitz',
            'Zone',
            'Man',
            'Tempo',
            'Clutch',
            'Pressure',
            'Momentum',
            'Injury',
            'Scheme',
            'Hero',
          ],
        },
        {
          type: 'labeled',
          label: 'Weak tag system',
          lines: [
            'Goblin',
            'Forest',
            'Turn 3',
            'Blue card',
            'Left lane',
            'Specific boss name',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Does each tag appear on multiple cards?',
            'Does each tag have enablers and payoffs?',
            'Can enemies interact with tags?',
            'Can rewards reference tags?',
            'Can upgrades modify tags?',
            'Are there any tags used by only one card?',
          ],
        },
      ],
      rule: 'If a tag appears on only one card, it probably should not be a tag yet.',
    },
    {
      number: 4,
      title: 'Every archetype needs enablers and payoffs',
      paragraphs: [
        'An archetype is not just a theme. It is a repeatable pattern of play.',
        'Each archetype needs:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Core action',
            'Cheap enabler',
            'Defensive tool',
            'Card draw or resource support',
            'Payoff',
            'Rare build-around',
            'Weakness',
            'Enemy counterpressure',
          ],
        },
        {
          type: 'labeled',
          label: 'Example archetype: Tempo',
          lines: [
            'Core action:',
            'Quick Strike',
            '',
            'Enabler:',
            'Play a Quick card to draw 1.',
            '',
            'Defense:',
            'Gain Block when you play 3 cards in a turn.',
            '',
            'Payoff:',
            'Deal bonus damage for each card played this turn.',
            '',
            'Rare build-around:',
            'The first Quick card each turn costs 0.',
            '',
            'Weakness:',
            'Runs out of cards without draw support.',
            '',
            'Enemy counterpressure:',
            'Enemies that punish playing too many cards.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Can the player recognize this archetype after seeing 3 to 5 cards?',
            'Does the archetype have more than one path to function?',
            'Does it have a weakness?',
            'Does it have a payoff worth building toward?',
            'Can it mix with another archetype?',
          ],
        },
      ],
      rule: 'Start with 3 archetypes. Do not build 8 weak archetypes.',
    },
    {
      number: 5,
      title: 'Separate baseline value from conditional upside',
      paragraphs: [
        'A good card often has a baseline effect and a conditional bonus.',
        'This keeps the card useful while still rewarding smart play.',
      ],
      blocks: [
        {
          type: 'labeled',
          label: 'Weak',
          lines: [
            'If you played a Quick card this turn, deal 12 damage.',
            'Otherwise, do nothing.',
          ],
        },
        {
          type: 'labeled',
          label: 'Better',
          lines: [
            'Deal 6 damage.',
            'If you played a Quick card this turn, deal 4 more.',
          ],
        },
        {
          type: 'labeled',
          label: 'For a football card',
          lines: [
            'Gain +2 yards.',
            'If this is a Quick Pass, gain +3 more yards.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Does the card do something without its condition?',
            'Is the conditional bonus exciting but not mandatory?',
            'Is the condition readable before the player commits?',
            'Does the bonus support the card’s archetype?',
          ],
        },
      ],
      rule: 'Most common cards should have safe baseline value. Rare cards can be more conditional.',
    },
    {
      number: 6,
      title: 'Costs should create tradeoffs',
      paragraphs: [
        'Cost is not just a number. Cost is how the card asks a question.',
        'Possible costs:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Energy',
            'Gold',
            'Health',
            'Discard',
            'Exhaust',
            'Drawback',
            'Cooldown',
            'Limited uses',
            'Risk of curse',
            'Opportunity cost',
            'Consumes status',
            'Ends turn',
          ],
        },
        {
          type: 'labeled',
          label: 'Bad cost design',
          lines: ['Every good card costs 1.', 'Every bad card costs 2.'],
        },
        {
          type: 'labeled',
          label: 'Better cost design',
          lines: [
            'Cheap cards enable tempo.',
            'Expensive cards create big turns.',
            'Free cards require setup or have drawbacks.',
            'Risk cards are powerful but can backfire.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Would I ever choose not to play this card?',
            'Is the card too efficient for its cost?',
            'Does the cost match the effect size?',
            'Does the cost support the intended archetype?',
            'Can the player understand the tradeoff quickly?',
          ],
        },
      ],
      rule: 'Use one primary resource at first. Add alternate costs only when the core loop is already clear.',
    },
    {
      number: 7,
      title: 'Draw and energy are dangerous',
      paragraphs: [
        'Card draw and energy generation are usually the easiest ways to break a deckbuilder.',
        'Watch these effects carefully:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Draw cards',
            'Gain energy',
            'Reduce costs',
            'Create free cards',
            'Repeat previous card',
            'Copy cards',
            'Play cards from discard',
            'Retain cards',
            'Search deck',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Can this card replace itself?',
            'Can this card generate more resources than it costs?',
            'Can it be copied?',
            'Can it reduce the cost of another draw or energy card?',
            'Can multiple copies chain together?',
            'Does it need exhaust, once-per-turn, or a cap?',
          ],
        },
        {
          type: 'labeled',
          label: 'Common safety valves',
          lines: [
            'Exhaust after use',
            'Once per turn',
            'Draw next turn instead of now',
            'Cost cannot be reduced below 1',
            'Created cards are temporary',
            'Effect does not trigger from copied cards',
            'Limit by tag or card type',
          ],
        },
      ],
      rule: 'Be conservative with draw, cost reduction, and energy generation until you have playtest data.',
    },
    {
      number: 8,
      title: 'Rarity should change complexity, not just power',
      paragraphs: [
        'Common cards should teach the game.',
        'Uncommon cards should connect systems.',
        'Rare cards should bend rules.',
      ],
      blocks: [
        {
          type: 'labeled',
          label: 'Common',
          lines: ['Simple, broadly useful, low complexity.'],
        },
        {
          type: 'labeled',
          label: 'Uncommon',
          lines: ['More conditional, supports archetypes, creates stronger combos.'],
        },
        {
          type: 'labeled',
          label: 'Rare',
          lines: ['Build-around, rule-breaking, high upside, higher risk.'],
        },
        {
          type: 'labeled',
          label: 'Bad rarity',
          lines: ['Common: Deal 5.', 'Rare: Deal 20.'],
        },
        {
          type: 'labeled',
          label: 'Better rarity',
          lines: [
            'Common:',
            'Deal 6.',
            '',
            'Uncommon:',
            'Deal 5. Draw 1 if the enemy has Pressure.',
            '',
            'Rare:',
            'Whenever you draw a Quick card, gain 1 Momentum.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Are common cards readable in one sentence?',
            'Do uncommon cards connect tags and resources?',
            'Do rare cards change how the player builds?',
            'Are rares exciting without becoming automatic picks?',
            'Does the player understand why a card is rare?',
          ],
        },
      ],
      rule: 'Rares should create new deck direction, not simply bigger numbers.',
    },
    {
      number: 9,
      title: 'Upgrades should sharpen identity',
      paragraphs: ['An upgrade should make the card more interesting, not just bigger.'],
      blocks: [
        {
          type: 'labeled',
          label: 'Basic upgrades',
          lines: [
            'More damage',
            'More block',
            'Lower cost',
            'More draw',
            'Longer status duration',
          ],
        },
        {
          type: 'labeled',
          label: 'Better upgrades',
          lines: [
            'Adds a tag',
            'Removes a drawback',
            'Adds conditional upside',
            'Changes timing',
            'Makes the card retain',
            'Adds exhaust for bigger impact',
            'Turns setup into payoff',
          ],
        },
        {
          type: 'labeled',
          label: 'Example',
          lines: [
            'Base:',
            'Deal 6. If you played a Quick card, draw 1.',
            '',
            'Upgrade A:',
            'Deal 8. If you played a Quick card, draw 1.',
            '',
            'Upgrade B:',
            'Deal 6. Gains the Combo tag. If you played a Quick card, draw 1.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Does the upgrade support the card’s role?',
            'Does it create a real choice?',
            'Does it make the card too efficient?',
            'Could the upgrade add identity instead of raw numbers?',
          ],
        },
      ],
      rule: 'Use one upgrade path at first. Add branching upgrades later.',
    },
    {
      number: 10,
      title: 'Status effects need clear ownership',
      paragraphs: ['Status systems get confusing fast.', 'Every status should answer:'],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Who owns it?',
            'When does it trigger?',
            'When does it decay?',
            'Can it stack?',
            'Is it consumed?',
            'Does it affect cards, enemies, or the whole turn?',
          ],
        },
        {
          type: 'labeled',
          label: 'Example status: Pressure',
          lines: [
            'Owner: Enemy',
            'Trigger: Player resolves attack cards.',
            'Effect: Attacks against this enemy deal +1.',
            'Decay: Loses 1 stack at end of turn.',
            'Stacking: Yes.',
          ],
        },
        {
          type: 'labeled',
          label: 'Bad status',
          lines: ['Momentum means you are stronger sometimes.'],
        },
        {
          type: 'labeled',
          label: 'Better status: Momentum',
          lines: [
            'Owner: Player',
            'Effect: The next scoring card gains +1 power per Momentum.',
            'Decay: All Momentum is removed after a scoring attempt.',
            'Stacking: Yes.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Can the player predict what the status will do?',
            'Does the UI show the status clearly?',
            'Does the status decay consistently?',
            'Does the status create decisions?',
            'Is this status different enough from other statuses?',
          ],
        },
      ],
      rule: 'Start with 3 to 5 statuses maximum.',
    },
    {
      number: 11,
      title: 'Enemy interaction makes cards matter',
      paragraphs: [
        'Cards feel better when enemies pressure the player’s deck choices.',
        'Enemy pressure can punish or reward:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Playing many cards',
            'Playing one big card',
            'Hoarding energy',
            'Discarding',
            'Blocking',
            'Attacking',
            'Using a specific tag',
            'Scaling slowly',
            'Ignoring defense',
            'Repeating the same action',
          ],
        },
        {
          type: 'labeled',
          label: 'Example',
          lines: [
            'Enemy:',
            'Mirror Knight',
            '',
            'Pressure:',
            'Gains strength when the player plays the same card type twice in a row.',
            '',
            'Counterplay:',
            'Mix attacks, skills, and setup cards.',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Does each enemy make certain cards more or less valuable?',
            'Can the player see the pressure before acting?',
            'Is there counterplay?',
            'Does the enemy teach a system?',
            'Does the enemy avoid hard-countering one build completely?',
          ],
        },
      ],
      rule: 'Enemies should pressure behavior, not invalidate whole archetypes.',
    },
    {
      number: 12,
      title: 'Remove cards that only add math',
      paragraphs: [
        'A card can be balanced and still be boring.',
        'Boring card patterns:',
      ],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Gain +1.',
            'Gain +2 instead.',
            'Deal 6.',
            'Deal 7 if condition is met.',
            'Small number changes with no decision.',
          ],
        },
        {
          type: 'labeled',
          label: 'Better cards change timing, risk, sequencing, or deck direction. Ask',
          lines: [
            'Does this card change how I play the turn?',
            'Does this card change what I want to draft later?',
            'Does this card make me care about sequencing?',
            'Does this card create a fun risk?',
            'Does this card help define an archetype?',
          ],
        },
      ],
      rule: 'If two cards create the same decision, merge them.',
    },
    {
      number: 13,
      title: 'Use this card review template',
      paragraphs: ['For every card, fill this out:'],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Name:',
            'Type:',
            'Cost:',
            'Rarity:',
            'Tags:',
            'Effect:',
            'Baseline value:',
            'Conditional upside:',
            'Design role:',
            'Archetype:',
            'Best-case use:',
            'Worst-case use:',
            'Dead-card risk:',
            'Combo hooks:',
            'Balance risk:',
            'Upgrade idea:',
            'Should this stay in the MVP?',
          ],
        },
        {
          type: 'labeled',
          label: 'Example',
          lines: [
            'Name:',
            'Hurry-Up Drill',
            '',
            'Type:',
            'Skill',
            '',
            'Cost:',
            '1',
            '',
            'Rarity:',
            'Uncommon',
            '',
            'Tags:',
            'Tempo, Draw, Setup',
            '',
            'Effect:',
            'Draw 2. The next Quick card you play this turn costs 1 less.',
            '',
            'Baseline value:',
            'Draw 2.',
            '',
            'Conditional upside:',
            'Discounts a Quick card.',
            '',
            'Design role:',
            'Tempo enabler.',
            '',
            'Archetype:',
            'Quick/Tempo.',
            '',
            'Best-case use:',
            'Draws into a Quick card and enables a larger combo turn.',
            '',
            'Worst-case use:',
            'Draws cards but misses the Quick payoff.',
            '',
            'Dead-card risk:',
            'Low because it still draws.',
            '',
            'Combo hooks:',
            'Quick, cost reduction, card-play-count payoffs.',
            '',
            'Balance risk:',
            'May chain too easily with other draw cards.',
            '',
            'Upgrade idea:',
            'Draw 2. The next Quick or Combo card costs 1 less.',
            '',
            'Should this stay in the MVP?',
            'Yes, but test for draw-loop abuse.',
          ],
        },
      ],
    },
    {
      number: 14,
      title: 'MVP card pool checklist',
      paragraphs: ['A first testable card pool should include:'],
      blocks: [
        {
          type: 'lines',
          lines: [
            '10 core actions',
            '6 defensive cards',
            '6 draw/resource cards',
            '6 archetype enablers',
            '6 archetype payoffs',
            '3 rare build-arounds',
            '3 curses/status cards',
          ],
        },
        {
          type: 'labeled',
          label: 'Total',
          lines: ['35 to 40 cards'],
        },
        {
          type: 'labeled',
          label: 'For each archetype, include',
          lines: [
            '2 common enablers',
            '2 common payoffs',
            '1 defensive support card',
            '1 uncommon connector',
            '1 rare build-around',
            '1 enemy or encounter that pressures it',
          ],
        },
        {
          type: 'labeled',
          label: 'Checklist',
          lines: [
            'Are there enough common cards to build a coherent deck?',
            'Can each archetype function without rares?',
            'Can archetypes mix?',
            'Are there obvious trap cards?',
            'Are any cards automatic picks?',
            'Are any cards never picked?',
            'Does the pool have enough defense?',
            'Does the pool have enough draw?',
            'Does the pool have enough ways to spend resources?',
          ],
        },
      ],
      rule: 'The first card pool should prove the archetypes, not exhaust every idea.',
    },
    {
      number: 15,
      title: 'Final card system audit',
      paragraphs: ['Before adding more cards, ask:'],
      blocks: [
        {
          type: 'lines',
          lines: [
            'Can the player understand the card in 3 seconds?',
            'Can the card be useful in normal fights?',
            'Does it support a broad tag or archetype?',
            'Does it create a sequencing decision?',
            'Does it have a cost or tradeoff?',
            'Does it avoid breaking draw or energy economy?',
            'Does it interact with enemies, rewards, or upgrades?',
            'Does it add something meaningfully different from existing cards?',
            'Does it make the game more fun, not just bigger?',
          ],
        },
        {
          type: 'labeled',
          label: 'Cut the card if',
          lines: [
            'It only works in one rare situation.',
            'It requires too much explanation.',
            'It is always correct to play.',
            'It is never correct to pick.',
            'It duplicates another card’s role.',
            'It exists only because the theme is funny.',
            'It adds math without changing decisions.',
          ],
        },
      ],
      closingParagraphs: [
        'The best card systems are not large. They are legible, reusable, and explosive under pressure.',
        'A good MVP card does three things:',
        'It is understandable. It is useful. It points toward a build.',
        'If your card pool does that with 35 cards, you have enough to start playtesting.',
      ],
    },
  ],

  relatedLinks: [
    {
      label: 'Roguelike Deckbuilder Designer GPT',
      href: gptUrl,
    },
    {
      label: 'Roguelike Deckbuilder MVP Playbook',
      href: '/playbooks/roguelike-deckbuilder-mvp/',
    },
    {
      label: 'Card System Design for Indie Games',
      href: '/playbooks/card-system-design/',
    },
    {
      label: 'Cursor Spec for Card Game MVPs',
      href: '/playbooks/cursor-spec-for-card-games/',
    },
  ],

  closingCta: {
    heading: 'Design cards that point toward a build.',
    copy: 'Use the GPT to generate and audit card systems, then use the MVP playbook to scope your first playable prototype.',
    label: 'Open Roguelike Deckbuilder Designer GPT',
    href: gptUrl,
  },
};
